<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>
  <script>
    const p1 = new Promise((resolve, reject) => {
      // resolve("promise1")
      reject("catch1")
    }).then(res => { }).catch(res => { })
    const p2 = new Promise((resolve, reject) => {
      // resolve("promise2")
      reject("catch2")
    }).then(res => { }).catch(res => { })
    const p3 = new Promise((resolve, reject) => {
      // resolve("promise3")
      reject('catch3')
    }).then(res => { }).catch(res => { console.log(res) })

    // 如果上面的promise自己提供了catch那么将不会调用promise.all提供的catch。但是会调用then方法。
    Promise.all([p1, p2, p3]).then(res => {
      console.log("resolve", res)
    }).catch(res => {
      console.log("reject", res)
    })
  </script>
</body>

</html>